name: dnd_gui_angular2
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
#  angular2: 2.0.0-beta.19
  angular2: "^3.0.0"
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  ng_bootstrap: any
  dart_sass_transformer: any
transformers:
- dart_sass_transformer
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
